name: Python Workflow for Sum Frequencies Application
on:
  workflow_dispatch:

jobs:
  build:
    strategy: 
      fail-fast: false
      matrix:
        version: ["3.8", "3.9", "3.10"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            version: 3.7
        exclude:
          - platform: windows-latest
            version: 3.10

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r src/ch2/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test the application with mock data
      run: |
        python src/ch2/sum_frequency.py src/ch2/MOCK_DATA.json